sudo: required

dist: trusty

language: node_js

node_js:
  - '6'

python:
  - '2.7'

cache:
  directories:
    - "~/.platformio"

install:
  - npm install
  - pip install -U platformio

# test
script:
  - npm test
  - script/cibuild

# deploy
after_success:
  - script/deploy
