language: python

python:
  - '2.7'

sudo: false

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

before_script:
  - script/bootstrap

# test
script:
  - script/cibuild

# deploy
after_success:
  - script/deploy
